#!/bin/sh

set -e
set -x

result=$(mktemp)

test/specrunner \
'Content-Type: *.jpg image/jpeg, ! *.txt text/html; Content-Disposition: * "attachment; filename=foo.txt"' \
/bar.html >$result

grep "Content-Type: text/html" $result
grep "Content-Disposition: attachment; filename=foo.txt" $result

rm $result

