#!/bin/sh

set -e
set -x

result=$(mktemp)

test/specrunner \
'Content-Type: *.css text/css, /blog/code/*/repository/raw/* text/plain, /blog/code/* text/html' \
/blog/code/foo >$result

grep "Content-Type: text/html" $result

rm $result


